/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.management;

import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class Category extends javax.swing.JPanel {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        lblHighlight.setBackground(new Color(147,193,120));
        lblHighlight.setOpaque(true);
        
        lblAddCategory.setBackground(new Color(70,91,140));
        lblAddCategory.setOpaque(true);
        lblAddCategory.setHorizontalAlignment(SwingConstants.CENTER);
        
        lblUpdateCategory.setBackground(new Color(147,193,120));
        lblUpdateCategory.setOpaque(true);
        lblUpdateCategory.setHorizontalAlignment(SwingConstants.CENTER);
        lblUpdateCategory.setVisible(false);
        
        lblDellCategory.setBackground(Color.red);
        lblDellCategory.setOpaque(true);
        lblDellCategory.setHorizontalAlignment(SwingConstants.CENTER);
        lblDellCategory.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblAddCategory = new javax.swing.JLabel();
        lblUpdateCategory = new javax.swing.JLabel();
        lblDellCategory = new javax.swing.JLabel();
        lblHighlight = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1720, 2000));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"MH001", "Lemon tea", "Ly", "15,000", "10,000"},
                {"MH002", "Peach tea", "Ly", "15,000", "10,000"},
                {"MH003", "Heo quay", "Phần", "50,000", "30,000"},
                {"MH004", "Cá kho", "Phần", "30,000", "20,000"},
                {"MH005", "Canh chua", "Phần", "30,000", "20,000"},
                {"MH006", "Trứng chiên ", "Phần", "15,000", "10,000"},
                {"MH007", "Thuốc lá", "Gói", "30,000", "20,000"},
                {"MH008", "Bia ", "Thùng ", "400,000", "350,000"},
                {"MH009", "Coca", "Lon ", "15,000", "10,000"}
            },
            new String [] {
                "Mã hàng hóa", "Tên hàng hóa", "Đơn vị tính", "Giá bán", "Giá vốn "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 522, 1644, 751));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Danh Sách Hàng Hóa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(70, 92, 139));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 131, 1610, 9));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hàng hóa", "Tên hàng hóa", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 50));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("NV001");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 320, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Search_50px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        lblAddCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblAddCategory.setText("Thêm mới");
        jPanel1.add(lblAddCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 380, 200, 50));

        lblUpdateCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUpdateCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateCategory.setText("Cập nhật");
        jPanel1.add(lblUpdateCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 380, 150, 50));

        lblDellCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDellCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblDellCategory.setText("Xóa");
        jPanel1.add(lblDellCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 380, 150, 50));
        jPanel1.add(lblHighlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 10, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        lblUpdateCategory.setVisible(true);
        lblDellCategory.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAddCategory;
    private javax.swing.JLabel lblDellCategory;
    private javax.swing.JLabel lblHighlight;
    private javax.swing.JLabel lblUpdateCategory;
    // End of variables declaration//GEN-END:variables
}
