/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.management;

import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class Customer extends javax.swing.JPanel {

    /**
     * Creates new form customer
     */
    public Customer() {
        initComponents();
        lblHighlight.setBackground(new Color(147,193,120));
        lblHighlight.setOpaque(true);
        
        lblAddCustomer.setBackground(new Color(70,91,140));
        lblAddCustomer.setOpaque(true);
        lblAddCustomer.setHorizontalAlignment(SwingConstants.CENTER);
        
        lblDellCustomer.setBackground(Color.red);
        lblDellCustomer.setOpaque(true);
        lblDellCustomer.setHorizontalAlignment(SwingConstants.CENTER);
        lblDellCustomer.setVisible(false);
        
        lblUpdateCustomer.setBackground(new Color(147,193,120));
        lblUpdateCustomer.setOpaque(true);
        lblUpdateCustomer.setHorizontalAlignment(SwingConstants.CENTER);
        lblUpdateCustomer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblUpdateCustomer = new javax.swing.JLabel();
        lblDellCustomer = new javax.swing.JLabel();
        lblAddCustomer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHighlight = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1600, 2000));
        setPreferredSize(new java.awt.Dimension(1600, 2000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KH001", "Sơn TùngMTP", "Kim Cương", "10,000,000"},
                {"KH002", "Đông Nhi", "Vàng", "5,000,000"},
                {"KH003", "Noo Phước Thịnh", "Bạc", "3,000,000"},
                {"KH004", "Tóc Tiên", "Kim Cương", "40,000,000"}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Loại khánh hàng", "Tổng bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 461, 1680, 956));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã khách hàng", "Tên khách hàng", "Loại khách hàng" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 342, 203, 53));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("KH001");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 342, 332, 53));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Search_50px.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 342, -1, 53));

        lblUpdateCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUpdateCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateCustomer.setText("Cập nhật");
        add(lblUpdateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1067, 342, 181, 53));

        lblDellCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDellCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblDellCustomer.setText("Xóa");
        add(lblDellCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 340, 181, 52));

        lblAddCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblAddCustomer.setText("Thêm Khách hàng");
        add(lblAddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 342, 222, 53));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Khách Hàng");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(70, 92, 139));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 130, 1610, 10));
        add(lblHighlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 10, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        lblUpdateCustomer.setVisible(true);
        lblDellCustomer.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAddCustomer;
    private javax.swing.JLabel lblDellCustomer;
    private javax.swing.JLabel lblHighlight;
    private javax.swing.JLabel lblUpdateCustomer;
    // End of variables declaration//GEN-END:variables
}
