/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.management;

import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class Supplier extends javax.swing.JPanel {

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        lblHighlight.setBackground(new Color(147,193,120));
        lblHighlight.setOpaque(true);
        
        lblAddSupplier.setBackground(new Color(70,91,140));
        lblAddSupplier.setOpaque(true);
        lblAddSupplier.setHorizontalAlignment(SwingConstants.CENTER);
        
        lblUpdateSupplier.setBackground(new Color(147,193,120));
        lblUpdateSupplier.setOpaque(true);
        lblUpdateSupplier.setHorizontalAlignment(SwingConstants.CENTER);
        lblUpdateSupplier.setVisible(false);
        
        lblDelSupplier.setBackground(Color.red);
        lblDelSupplier.setOpaque(true);
        lblDelSupplier.setHorizontalAlignment(SwingConstants.CENTER);
        lblDelSupplier.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblAddSupplier = new javax.swing.JLabel();
        lblUpdateSupplier = new javax.swing.JLabel();
        lblDelSupplier = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHighlight = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1720, 2000));

        jPanel1.setMinimumSize(new java.awt.Dimension(1720, 2000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1720, 2000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"NCC001", "Công ty TNHH Citigo", "090123123", "", "0", "213,000,000"},
                {"NCC002", "Công ty Hoàng Gia", "0123123123", null, "0", "200,000,000"},
                {"NCC003", "Công ty Pharmedic", "0123324", null, "0", "19,000,000"},
                {"NCC004", "Đại lý Hồng Phúc", "0454554", null, "0", "30,000,000"},
                {"NCC005", "Cửa hàng Đại Việt", "0955555", null, "0", "90,000,000"},
                {"NCC006", "Big C", "09888889", null, "0", "12,000,000"},
                {"NCC007", "Công ty hải sản Sea", "09666666", null, "0", "30,000,000"},
                {"NCC008", "Công ty Vu Nguyen", "09444444", null, "0", "50,000,000"},
                {"NCC009", "Công ty Hữu Nam", "09232323", null, "0", "40,000,000"}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Số điện thoại", "Email", "Công nợ", "Tổng mua"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 1670, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Nhà Cung Cấp");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã nhà cung cấp", "Tên nhà cung cấp", "Số điện thoại" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 210, 50));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("NCC001");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 320, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Search_50px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        lblAddSupplier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblAddSupplier.setText("Thêm NCC");
        jPanel1.add(lblAddSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 150, 60));

        lblUpdateSupplier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUpdateSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateSupplier.setText("Cập nhật");
        jPanel1.add(lblUpdateSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 263, 190, 60));

        lblDelSupplier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDelSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblDelSupplier.setText("Xóa");
        jPanel1.add(lblDelSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 260, 190, 60));

        jSeparator1.setBackground(new java.awt.Color(70, 92, 139));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 131, 1610, 9));
        jPanel1.add(lblHighlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 10, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        lblUpdateSupplier.setVisible(true);
        lblDelSupplier.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAddSupplier;
    private javax.swing.JLabel lblDelSupplier;
    private javax.swing.JLabel lblHighlight;
    private javax.swing.JLabel lblUpdateSupplier;
    // End of variables declaration//GEN-END:variables
}
